Move temp directory creation/cleanup to the wrapper script; Also some editorial changes for consistency

diff --git a/sbin/a3_update_wrapper b/sbin/a3_update_wrapper
--- a/sbin/a3_update_wrapper
+++ b/sbin/a3_update_wrapper
@@ -1,6 +1,17 @@
 #!/bin/sh
 
-/usr/local/pf/sbin/a3_update
+LOGFILE=/usr/local/pf/logs/a3_update.log
+TMPDIR=`/usr/bin/mktemp -d -p /tmp a3_update.XXXXXXXX`
+
+if [ $? -ne 0 ]; then
+    echo "Unable to create workspace for update" >> $LOGFILE
+    exit 1
+fi
+
+/usr/local/pf/sbin/a3_update $TMPDIR
 
 # Be sure to clean up lock file
 /usr/bin/rm -f /usr/local/pf/var/run/update.lock
+
+# Be sure to remove tmpdir
+/usr/bin/rm -rf $TMPDIR
